#!/bin/bash
##PBS -W group_list=uafaqua
##PBS -q standard_16
##PBS -l walltime=3:00:00
##PBS -l nodes=15:ppn=16
##PBS -j oe
#. /opt/modules-3.2.6/Modules/3.2.6/init/bash
#export MODULES_NO_OUTPUT=1
#module load /home/qiu05/own.modules
#export -n MODULES_NO_OUTPUT

cd /home/qiu05/genx_pc_qiu/MPI_run_files/temp_gx_files

file=$(date +'*_%b%d.gx')
while  [ `ls $file | wc -l` != 0 ]
do
    for gx in $file;do
	if [ `ls $file | wc -l` != 0 ] ;
	then
        eval "export `mpirun env | grep OMPI_MCA_orte_precondition_transports`"
	mpiexec --mca mpi_warn_on_fork 0 -np 256  python /home/qiu05/genx_pc_qiu/MPI_run_files/GenX_run_multiple_mpi_new_3.py $gx 256 2>&1 |tee job.$PBS_JOBID.out 
	rm -f $gx;
	else
	sleep 1
	fi;
    done
done
rm -f *.o*
rm -f *.e*
